# Generated by Django 5.0.6 on 2024-09-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_memo_review_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='memo',
        ),
    ]
