# Generated by Django 5.0.6 on 2024-09-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=33)),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Purchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=33)),
                ('description', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
