# Generated by Django 5.0.6 on 2024-09-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_purchased_delete_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchased',
        ),
    ]
