# Generated by Django 5.0.6 on 2024-09-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchased', '0003_remove_purchased_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='image',
            field=models.ImageField(default=1, upload_to='products/images/'),
            preserve_default=False,
        ),
    ]
