# Generated by Django 5.1.1 on 2024-10-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchased', '0004_purchased_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('in_transit', 'В пути'), ('arrived', 'Прибыл')], default='pending', max_length=20),
        ),
    ]
