# Generated by Django 5.1.1 on 2024-10-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchased', '0005_purchased_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('В пути', 'В пути'), ('Прибыл', 'Прибыл')], default='pending', max_length=20),
        ),
    ]
